/* Generated with cbindgen:0.16.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef enum vibrant_Backend {
  XNVCtrl,
  CTM,
} vibrant_Backend;

typedef enum vibrant_Error {
  Ok,
  OpenDisplay,
  NullName,
  BadName,
  OutOfRange,
} vibrant_Error;

size_t vibrant_instance_controllers_size(vibrant_Instance *instance);

void vibrant_instance_free(vibrant_Instance *instance);

enum vibrant_Error vibrant_instance_from_display_name(const char *name, vibrant_Instance *ret);

enum vibrant_Error vibrant_instance_get_controller_backend(vibrant_Instance *instance,
                                                           size_t idx,
                                                           enum vibrant_Backend *backend);

enum vibrant_Error vibrant_instance_get_controller_name(vibrant_Instance *instance,
                                                        size_t idx,
                                                        const unsigned char **str,
                                                        size_t *len);

enum vibrant_Error vibrant_instance_get_controller_saturation(vibrant_Instance *instance,
                                                              size_t idx,
                                                              double *saturation);

enum vibrant_Error vibrant_instance_new(vibrant_Instance *ret);

enum vibrant_Error vibrant_instance_set_controller_saturation(vibrant_Instance *instance,
                                                              size_t idx,
                                                              double saturation);
